sudo: false
language: rust

rust:
  - nightly
  - stable
  - beta
  - 1.31.0

before_script:
  - set -o errexit

script:
  - shopt -s expand_aliases
  - alias build="cargo build ${TARGET+--target=$TARGET}"
  - build
  - build --all-features

matrix:
  include:
    - rust: nightly
      name: Tests
      script:
        - cargo test --all-features --release
    - rust: nightly
      name: Examples
      script:
        - cargo check --manifest-path examples/json2rust/Cargo.toml
        - cargo check --manifest-path examples/rust2json/Cargo.toml
    - rust: nightly
      name: Minimal versions
      script:
        - cargo update -Z minimal-versions
        - cargo build --all-features
    - rust: nightly
      name: Clippy
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy --all-features -- -Dwarnings
    - rust: stable
      name: Rustfmt
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check
        - cd "${TRAVIS_BUILD_DIR}/examples/json2rust" && cargo fmt -- --check
        - cd "${TRAVIS_BUILD_DIR}/examples/rust2json" && cargo fmt -- --check
  fast_finish: true

env:
  global:
    - RUST_MIN_STACK=20000000

notifications:
  email:
    on_success: never
